# Generated by Django 3.2.2 on 2021-05-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsite', '0002_auto_20210517_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='first published at'),
        ),
    ]
