# Generated by Django 3.2.2 on 2021-05-17 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitorsite', '0003_alter_page_first_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visitorsite.page')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Header Image')),
            ],
            bases=('visitorsite.page',),
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Main content section '),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', verbose_name='SEO meta description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, verbose_name='SEO title tag'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('headshot', models.ImageField(upload_to='authors_headshot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='blog_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='visitorsite.blog', verbose_name='creator'),
        ),
    ]
