# Generated by Django 3.2.2 on 2021-05-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsite', '0005_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='live',
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'UnPublished'), (2, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_page',
            field=models.ForeignKey(blank=True, help_text="Blog Page that this post will be residing in it's listing", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='visitorsite.blog', verbose_name='Blog Page'),
        ),
    ]
