# Generated by Django 3.2.2 on 2021-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsite', '0006_auto_20210519_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='first_published_at',
        ),
        migrations.AddField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created On'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
    ]
