# Generated by Django 3.2.2 on 2021-05-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsite', '0007_auto_20210519_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='main',
            new_name='body',
        ),
    ]
